### ISSUE TITLE
【質問】UnregisterAllSuccess.RegistListの型について

### ISSUE THREAD

**Issue by h-tsun3** [kabucom/kabusapi#640]
OpenAPI定義ファイル 5805行目に「type: "object"」と記述されていますが、正しくは「type: "array"」ではないでしょうか？

```
    UnregisterAllSuccess:
      type: "object"
      properties:
        RegistList:
          description: "現在登録されている銘柄のリスト<br>※銘柄登録解除が正常に行われれば、空リストを返します。<br>　登録解除でエラー等が発生した場合、現在登録されている銘柄のリストを返します"
          type: "object"
          example: []
```
          
同様にRegistListを返すRegistSuccessの方は「type: "array"」となっています。
